spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001

eureka: 
  instance:
    hostname: eureka7001.com 
    instance-id: eureka7001.com
    prefer-ip-address: true
  client:
    service-url: 
      defaultZone: http://edmin:edmin@eureka7002.com:7002/eureka,http://edmin:edmin@eureka7003.com:7003/eureka
    register-with-eureka: false   #当前服务部注册到eureka里面
    fetch-registry: false         #不通过eureka获取注册信息
spring:
  profiles: dev
  application:
    name: eureka-server-config-client
    
security:
  basic:
    enabled: true    # 启用安全认证处理
  user:
    name: edmindev     # 用户名
    password: edmin  # 密码
    
---
server:
  port: 7001

eureka: 
  instance:
    hostname: eureka7001.com 
    instance-id: eureka7001.com
    prefer-ip-address: true
  client:
    service-url: 
      defaultZone: http://edmin:edmin@eureka7002.com:7002/eureka,http://edmin:edmin@eureka7003.com:7003/eureka
    register-with-eureka: false   #当前服务部注册到eureka里面
    fetch-registry: false         #不通过eureka获取注册信息
spring:
  profiles: beta
  application:
    name: eureka-server-config-client
    
security:
  basic:
    enabled: true    # 启用安全认证处理
  user:
    name: edminbeta     # 用户名
    password: edmin  # 密码