spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8001
  
eureka:
  client:
    service-url: 
      defaultZone: http://edmin:edmin@eurekaserver.com:7001/eureka
  instance:
    instance-id: microdept.com
    prefer-ip-address: true
    
info: 
  app.name: www.microdept.com
  company.name: hlxd
  build.groupId: $project.groupId$
  build.artifactId: $project.artifactId$
  app.version: V33.3.3
      
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.hlxd.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2: 
      min-idle: 5                                
      initial-size: 5                              
      max-total: 5                                 
      max-wait-millis: 200        
  application:
    name: microcloud-provider-dept
  rabbitmq:
    host: rabbitmq.com
    port: 5672
    username: hlxd
    password: hlxd
    

---
server:
  port: 8002
  
eureka:
  client:
    service-url: 
      defaultZone: http://edmin:edmin@eureka7001.com:7001/eureka
  instance:
    instance-id: microdept8002.com
    prefer-ip-address: true
    
info: 
  app.name: www.microdept8002.com
  company.name: hlxd
  build.groupId: $project.groupId$
  build.artifactId: $project.artifactId$
  build.version: $project.version$
      
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.mldn.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
spring:
  profiles: beta
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2: 
      min-idle: 5                                
      initial-size: 5                              
      max-total: 5                                 
      max-wait-millis: 200        
  application:
    name: microcloud-provider-dept
  rabbitmq:
    host: rabbitmq.com
    port: 5672
    username: hlxd
    password: hlxd
